language: minimal
services:
  - docker
script:
  - docker build --no-cache --pull -t quay.io/wisvch/oidc-kubeconfig:$TRAVIS_BUILD_NUMBER .
deploy:
  provider: script
  script: sh -c 'docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io; docker push quay.io/wisvch/oidc-kubeconfig:$TRAVIS_BUILD_NUMBER'
  on:
    branch: master
notifications:
  email: false
  slack:
    rooms:
      secure: iXVCyCt9wGqjbwigOLQF2B+iB4nJ1P3W796eRXcb302XL2gBRaK3mS3nou28WGVYSEciqf65XCXEl00vOkAy1FP9cxIuYnEYxa03L59/Mfsxko0+thdic/CTEF1E4Igqo7SzFNz3+MhEQWB9AL/DpSszAdRnDmCBoJR6RvU7GiC8stuiDXUn1T0jCpZplh4SfnFHNQoC5Hjrv4fZewlHlW6PmWZGMyHFvqpz1bVXKgjbdIeLKEMb1kUHczd+SnmcfbAAdePb41VFMHi9RKJVi7rUF9eygOtRxmXCdIggUfyuPKkQPwvWzL0sdPqUFK4EDtX2TWQvV8RnY1P0lf2BZIHqo8LYrkW+A78tgPFjE9oQ2IC55edcywWiipRRgLpjnC/ZDUkqLoG6iMS4ZB5wlYXdzeC0BndSbANjxYoI09033Ls0WOydkdc5dwyiu28fb7MPLCAgoPOHw6cFkEmgwhXH6rlpw1ElWy9FPzXvLWOZBEo4OkJUb0lT9A6bDunW1DkiZTgh6yKvmj/cVjhIOb2sgD9iRnJ9QBpjTuPDSEb61eMaTJSrkhr5ran5PcyDEpqNWP8oiYmYNOA+1TVLZr168dmdXkUEykkvPHLIJoUhH8y4jtYpP5Lls8Ek9P1WNcJF8/yqNO0+hWWxNcoyvpa/pIwvX+aeGifrICOtA4A=
